# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e960c18143b30e38f70369d07c8be5b97740f80646b1f4d669fe4e4b81059d070558784b5dfddfadc8a584793a652f1de581a1e6371960014780a36f93303c

test:
  secret_key_base: cbedacf4502cf32c76abc37439963432df2e27abf38ed27e0c77ed213003441a9ba19da7f804da6ac1574dedbb38d05c2905138c91e7598c94d5421e9b453bb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
